/***************************** À exécuter ÉTAPE par ÉTAPE (CTRL+ENTER) en tant que AS SYSBDA *******************************/
SET SERVEROUTPUT ON;

--1. Création de l'utilisateur SECURITE sans privilèges, mais offrir l'espace de stockage suivant : quota 1M on users
--  D'abord utiliser un bloc anonyme comme dans les travaux pratiques pour vérifier s'il existe, le supprimer
declare
    existe number(1);
begin
    SELECT COUNT(*) INTO existe FROM dba_users WHERE username = 'SECURITE';
    
    IF existe = 1 THEN
        EXECUTE IMMEDIATE 'DROP USER SECURITE CASCADE';
    END IF;
    
    -- Ensuite, créer l'utilisateur (il faut que le script fasse tout le cycle : supprimer au besoin, puis recréer)
    EXECUTE IMMEDIATE 'CREATE USER SECURITE IDENTIFIED BY password QUOTA 1M ON users';
    DBMS_OUTPUT.PUT_LINE('L''utilisateur SECURITE a été créé avec succès.');
end;


--2. Création de la table PARAM_CHIFFREMENT si elle n'existe pas
--*** À développer ***
DECLARE 
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM ALL_TABLES WHERE OWNER = 'SECURITE' AND TABLE_NAME = 'PARAM_CHIFFREMENT';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE SECURITE.PARAM_CHIFFREMENT (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            code VARCHAR2(20),
            valeur VARCHAR2(1000)
        )';
    END IF;
END;

SELECT * FROM param_chiffrement;
--3. Insertion de la clé de chiffrement (instruction fournie)
insert into securite.param_chiffrement(code, valeur) values ('cle', rawtohex('/gGCjjfh67'));

--Ne pas oublier de faire un COMMIT
commit; 

--4. Déclaration du package CHIFFREMENT_PKG dans le compte de l'utilisateur SECURITE (instructions fournies)
create or replace package securite.chiffrement_pkg as 
    function crypter_fct (i_valeur in varchar2) return varchar2;
    function decrypter_fct (i_valeur in varchar2) return varchar2;
end chiffrement_pkg; 
/

--4B --> Ne pas oublier de compiler le PKB fourni

--5. Privilèges d'exécution pour SECURITE et CNC
--5A. Octroi du privilège d'exécuter le package SYS.dbms_crypto à Securite
--*** À développer ***

GRANT EXECUTE ON SYS.dbms_crypto TO securite;



--5B. Octroi du privilège d'exécuter le package securite.chiffrement_pkg à CNC
--*** À développer ***
GRANT EXECUTE ON securite.chiffrement_pkg TO cnc;